"""
Alert model - stores generated alerts from log analysis.
"""

from datetime import datetime, timezone

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Index,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class Alert(Base):
    """
    Represents an alert generated by the alert engine.

    Alert types:
        - high_error_rate: Error rate exceeds threshold
        - spam_ip: IP address sending too many requests
        - server_error: 5xx errors detected

    Severity levels:
        - info: Informational
        - warning: Needs attention
        - critical: Immediate action required
    """

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    alert_type: Mapped[str] = mapped_column(String(50), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="warning")
    message: Mapped[str] = mapped_column(Text, nullable=False)
    extra_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    is_resolved: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    __table_args__ = (
        Index("idx_alerts_created_at", "created_at", postgresql_using="brin"),
        Index("idx_alerts_type_resolved", "alert_type", "is_resolved"),
    )

    def __repr__(self) -> str:
        return (
            f"<Alert(id={self.id}, type={self.alert_type}, "
            f"severity={self.severity}, resolved={self.is_resolved})>"
        )
